### PR TITLE
Add "Now Playing" information to the top bar

### PR DESCRIPTION
**Pull request by ultrafez**
Information on what music is playing on a specified MPD server is displayed on the top status bar. The "Now Playing" text alternates with the "who's here" text every 10 seconds.

I have written a small Node daemon to connect to and handle events from MPD, which is configurable using a config.json file placed next to the provided config.json.example. This Node daemon exposes MPD events and information over a socket.io connection, which is received by the browser. At present, the connection publishes all of MPD's status and currentsong data, but only the track name and play status are actually used. The Node process should run under supervisord with auto-restart enabled, as the Node process will just kill itself if MPD errors or quits.

### CODE REVIEW

**Comment by hexwab** [comment]
I failed to get the daemon running on sauron with the example config. Maybe I'm doing it wrong?

```
hackspace@sauron:/srv/lhs-status/lhs-status/mpd-connector$ ln -s config.json.example config.json
hackspace@sauron:/srv/lhs-status/lhs-status/mpd-connector$ node index.js

/srv/lhs-status/lhs-status/mpd-connector/config.json.example:2
    "mpd": {
         ^
SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/lhs-status/lhs-status/mpd-connector/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Are you aware there's already a websocket service available? [ympd](http://www.ympd.org) is running on wifihifi:80.

**Comment by ultrafez** [comment]
I'm not sure of the cause of the syntax error - I've run it through a JSON validator and it reports that it's valid. It seems that it's trying to import the file as executable Javascript rather than as a JSON file - perhaps node is resolving the symlink, and because it doesn't recognise the .example extension, it defaults to trying to execute it rather than parse as JSON? Copying the example to config.json would prove/disprove that theory.

I wasn't aware that there was already a web interface running, I'm sure I tried accessing http://wifihifi.hackspace and nothing responded. However, if I can make use of the websocket provided by the existing web UI then it'll mean that we don't need the mpd-connector at all (less to maintain).

**Comment by ultrafez** [comment]
I investigated the websocket available as part of ympd, and it initally appeared to be suitable for our uses (it publishes title, artist and album information), but it doesn't appear to send track information when playing a radio stream. This is a limitation of ympd, rather than mpd, as third-party mpd clients receive track information about songs played in a radio stream, but ympd doesn't.

I've committed a simple ympd websocket client, but it's commented-out as it unfortunately doesn't receive enough data for our purposes. For this reason I would suggest using my mpd-connector as it does pass all data through to the client.

**Comment by ultrafez** [comment]
MPD is rarely used in the space any more, in favour of the 3.5mm audio cable, so I'm closing this pull request for now.

**Pull request closed without merging**
